repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
        name: gitleaks-secrets-scan
        args:
          - --config=.gitleaks.toml
        stages: [pre-commit]
